---
- name: Ensure installation scenario is selected
  fail:
    msg: "Please choose either the stable or git scenario."
  when:
    - not netbox_stable
    - not netbox_git

- name: Ensure only one scenario is enabled
  fail:
    msg: "Please select only one scenario."
  when:
    - netbox_stable and netbox_git

- name: Ensure a DB connection method is defined
  fail:
    msg: "Please define either database_socket (local) or database_host/database_password (TCP)."
  when:
    - netbox_database_socket is not defined
    - netbox_database_host is not defined or
      (netbox_database_host is defined and netbox_database_password is not defined)

- name: Ensure only one DB connection method is defined
  fail:
    msg: "Please define only one database connection method."
  when:
    - netbox_database_socket is defined and netbox_database_host is defined

- name: Ensure ALLOWED_HOSTS is defined
  fail:
    msg: "Please define ALLOWED_HOSTS in netbox_config."
  when: "'ALLOWED_HOSTS' not in netbox_config"

- name: Ensure NAPALM_USERNAME/PASSWORD is defined for NAPALM integration
  fail:
    msg: "Please define NAPALM_USERNAME and NAPALM_PASSWORD in netbox_config to use NAPALM."
  when:
    - netbox_napalm_enabled and ("NAPALM_USERNAME" not in netbox_config or "NAPALM_PASSWORD" not in netbox_config)

- name: Ensure MEDIA_ROOT is defined
  fail:
    msg: "Please define MEDIA_ROOT in netbox_config."
  when: "'MEDIA_ROOT' not in netbox_config"

- name: Ensure REPORTS_ROOT is defined
  fail:
    msg: "Please define REPORTS_ROOT in netbox_config."
  when: "'REPORTS_ROOT' not in netbox_config"
